#cloudbuild.yaml
steps:
- name: 'docker/compose:1.21.0'
  args: ['up', '-d']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_app:latest', 'gcr.io/$PROJECT_ID/core']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']